### PR TITLE
metadata search

### PR DESCRIPTION
**Pull request by boazin**
- merge of the changes made in origin yesterday (+sanity testing)
- Upgrade to Postgres9.4 (The only new diff is docker config)
- migration of test metadata to JSONB
- search ability (backend+frontend)

### CODE REVIEW

**Comment by vmalloc** [comment]
@boazin it seems the tests are failing on Travis... Can you take a look?

**Comment by boazin** [comment]
OK - so by default the alter_column is not using postgresql USING.
I'm still trying to verify if we can do it nice, otherwise I will change it to raw SQL

**Comment by boazin** [comment]
@vmalloc - albemic's author told me to make a pull request and add this feature to alembic (postgres_using)... :( - switched the upgrade script to raw SQL

**Comment by vmalloc** [comment]
Thanks!

**Pull request merged**
